version: '3'

services:
  ldap-server:
    build: ./openldap
    restart: always
    container_name: ldap-host
    environment:
      LDAP_ORGANISATION: "dmaf"
      LDAP_DOMAIN: "sora.com"
      LDAP_ADMIN_PASSWORD: "admin"
    networks:
      - webnet

  #cn=admin,dc=sora,dc=com


  ldap-admin:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "80:80"
    links:
      - "ldap-server:ldap"
    networks:
      - webnet

networks:
  webnet: